ToDoList/TDL.AspNet/Controllers/StatusController.cs
using System;
using System.Web.Mvc;
using TDL.WebApi.IService.IService;
using TDL.WebApi.Service.Models;

namespace TDL.AspNet.Controllers
{
    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;

        private  string _token;
        

        public StatusController(IStatusService statusService)
        {
            _statusService = statusService;
            _token = new Token().Tokens;
        }
        
        public ActionResult Index()
        {
            var statuses = _statusService.Get(_token);
            return View(statuses);
        }

        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            var status = _statusService.GetById(id, _token);
            return PartialView(status);
        }

        [HttpPost]
        public ActionResult Edit(StatusModel status)
        {
            try
            {
                _statusService.Update(status, _token);
            }
            catch (UnauthorizedAccessException)
            {
                Response.StatusCode = 401;
                return View();
            }
            return RedirectToAction("Index");
        }
        

        [HttpPost]
        public ActionResult Create(StatusModel status)
        {
            try
            {
                _statusService.Add(status, _token);
            }
            catch (UnauthorizedAccessException)
            {
                Response.StatusCode = 401;
                return View();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            try
            {
                _statusService.Delete(id, _token);
            }
            catch (UnauthorizedAccessException)
            {
                Response.StatusCode = 401;
                return View();
            }
            return RedirectToAction("Index");
        }
        
    }
}

ToDoList/TDL.AspNet/Views/Status/Edit.cshtml
@model TDL.WebApi.Service.Models.StatusModel
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container" id="editForm_@Model.IDStatus">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDStatus)

       
        <div class="form-group">
            <div class="input-group ">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
               
                <span class="input-group-btn">
                    <button class="btn btn-default btn-search " type="submit"><i class="fa fa-edit" aria-hidden="true"></i></button>
                    <i class="glyphicon glyphicon-remove" onclick="Cancel(@Model.IDStatus);" aria-hidden="true"></i>
                </span>
            </div>
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")

ToDoList/TDL.AspNet/Views/Status/Index.cshtml
@model IEnumerable<TDL.WebApi.Service.Models.StatusModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<button type="button" class="btn btn-primary col-lg-offset-4 d-block row top-margin " data-toggle="modal" data-target="#exampleModal">
    Add Status
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center text-info" id="exampleModalLabel">New Status</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="clear:both;"></div>
            <div class="modal-body row">
                @using (Html.BeginForm("Create", "Status"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal col-md-8 col-md-offset-2 text-center">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <div class="input-group ">
                                @Html.Editor("Name", new { htmlAttributes = new { @class = "form-control", maxlength = "50", required = "true", placeholder="New status name" } })
                                @Html.ValidationMessage("Name", "", new { @class = "text-danger" })
                                <span class="input-group-btn">
                                    <button class="btn btn-default btn-search " type="submit"><i class="fa fa-plus" aria-hidden="true"></i></button>
                                </span>
                            </div>
                        </div>
                    </div>
                }

            </div>
            <div style="clear:both;"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="list-group row col-lg-offset-4 col-md-4 top-margin">

    @foreach (var status in Model)
    {
        <p class="list-group-item ">
                @status.Name
            <a href="@Url.Action("Delete",  new { id = status.IDStatus })">
                <i class="fa fa-trash icons text-danger" aria-hidden="true"></i>
            </a>
            <a class="compItem" id="@status.IDStatus" href="@Url.Action("Edit",  new { id =status.IDStatus })">
                <i class="fa fa-edit icons text-success" aria-hidden="true"></i>
            </a>
        </p>
            <div id='modDialog'>
                <div id="dialogContent_@status.IDStatus"></div>
            </div>
    }
</div>

@Scripts.Render("~/category/script")