ToDoList/TDL.AspNet/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TDL.WebApi.IService.IModels;
using TDL.WebApi.IService.IService;
using TDL.WebApi.Service.Models;

namespace TDL.AspNet.Controllers
{
    public class CommentController : Controller
    {

        private readonly ICommentService _commentService;

        private string _token;
        

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
            _token = new Token().Tokens;
        }
        
        public PartialViewResult Index(int idTask)
        {
            ViewBag.IdTask = idTask;
            var comments = SwapToModels(_commentService.Get(idTask, _token));
            return PartialView(comments);
        }

        [HttpPost]
        public ActionResult Create(CommentModel comment)
        {
            comment.DateCreation = DateTime.Now;
            _commentService.Add(comment, _token);
            return RedirectToAction("Edit","Task", new { id= comment.IDTask } );
        }

        public ActionResult Delete(int id, int idTask)
        {
            _commentService.Delete(id, _token);
            return RedirectToAction("Edit", "Task", new { id = idTask });
        }

        private static CommentModel Swap(ICommentModel dto)
        {
            return new CommentModel
            {
                IDComment = dto.IDComment,
                IDTask = dto.IDTask,
                Description = dto.Description,
                DateCreation = dto.DateCreation,
                IDUser = dto.IDUser,
                User = dto.User
            };
        }

        private static List<CommentModel> SwapToModels(IEnumerable<ICommentModel> dtoes)
        {
            return dtoes.Select(Swap).ToList();

        }
    }
}

ToDoList/TDL.AspNet/Controllers/SharingTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TDL.WebApi.IService.IModels;
using TDL.WebApi.IService.IService;
using TDL.WebApi.Service.Models;

namespace TDL.AspNet.Controllers
{
    public class SharingTaskController : Controller
    {
        private readonly IUserService _userService;

        private readonly ISharedTaskService _sharedTaskService;

        private string _token;
        

        public SharingTaskController(IUserService userService, ISharedTaskService sharedTaskService)
        {
            _sharedTaskService = sharedTaskService;
            _userService = userService;
            _token = new Token().Tokens;
        }

        [HttpGet]
        public ActionResult Sharing(int idTask, string name )
        {
            ViewBag.TaskName = name;
            ViewBag.IdTask = idTask;
            return View();
        }

        public PartialViewResult AddedUser(int idTask)
        {
            var addedUser = _sharedTaskService.Get(idTask, _token);
            return PartialView(addedUser);
        }

        public PartialViewResult SearchUser(int idTask, string partName)
        {
            ViewBag.IdTask = idTask;
            var availableUser = SwapToUserModels(_userService.Get(partName, _token));
            var users = new List<ShortUserModel>();
            var addedUser = _sharedTaskService.Get(idTask, _token);
           
                for (var i = availableUser.Count() - 1; i >= 0; i--)
                {
                    foreach (var user in addedUser)
                    {
                        if (availableUser[i].IdUser == user.IDUser)
                            users.Add(availableUser[i]);
                    }
                }
            var result = availableUser.Except(users);
            return PartialView(result);
        }

        public void Delete(int id)
        {
            _sharedTaskService.Delete(id, _token);
        }

        public void CreateSharing(int idTask, int idUser)
        {
            _sharedTaskService.Add(new SharedTaskModel
            {
                IDTask = idTask,
                IDUser = idUser
            }, _token);
        }

        #region Swap

        private static SharedTaskModel SwapToModel(ISharedTaskModel dto)
        {
            return new SharedTaskModel
            {
                IDSharedTask = dto.IDSharedTask,
                IDTask = dto.IDTask,
                IDUser = dto.IDUser,
                User = dto.User
            };
        }

        private static IEnumerable<SharedTaskModel> SwapToModels(IEnumerable<ISharedTaskModel> dtoes)
        {
            return dtoes.Select(SwapToModel).ToList();

        }

        private static ShortUserModel SwapToUserModel(IShortUserModel dto)
        {
            return new ShortUserModel
            {
                UserName = dto.UserName,
                IdUser = dto.IdUser
            };
        }

        private static List<ShortUserModel> SwapToUserModels(IEnumerable<IShortUserModel> dtoes)
        {
            return dtoes.Select(SwapToUserModel).ToList();

        }

        #endregion
    }
}

ToDoList/TDL.AspNet/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TDL.AspNet.Models;
using TDL.AspNet.PaginationSetting;
using TDL.WebApi.IService.IModels;
using TDL.WebApi.IService.IService;
using TDL.WebApi.Service.Models;

namespace TDL.AspNet.Controllers
{
    public class TaskController : Controller
    {
        private readonly ITaskService _taskService;

        private readonly IStatusService _statusService;

        private readonly ICommentService _commentService;

        private string _token;

        private PaginationSeting _paginationSetting;
        

        public TaskController(ITaskService taskService, IStatusService statusService, ICommentService commentService)
        {
            _taskService = taskService;
            _statusService = statusService;
            _commentService = commentService;
            _paginationSetting = new PaginationSeting();
            _token = new Token().Tokens;
        }
        
        public PartialViewResult Index(int idCategory, int page = 1)
        {
            var tasks = SwapToModel(_taskService.Get(idCategory, _token, _paginationSetting.GetPaginationSetting(), page));
            return PartialView(tasks);
        }

        public ActionResult SharedTask(int page = 1)
        {
            var tasks = SwapToModel(_taskService.GetByUser(_token, _paginationSetting.GetPaginationSetting(), page));
            return View(tasks);
        }

        [HttpGet]
        public ActionResult Create(int idCategory)
        {
            ViewBag.IdCategory = idCategory;
            ViewBag.Statuses = new SelectList(SwapToStatusModels(_statusService.Get(_token)), "IDStatus", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateTaskModel task)
        {
            if (ModelState.IsValid)
            {
                task.DateCreation = DateTime.Now;
                _taskService.Add(SwapCreateModelToModel(task), _token);
                return RedirectToAction("Index", "Category");
            }
            return View();
        }

        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var task = SwapModelToCreateModel( _taskService.GetById(id, _token));
            var statuses = SwapToStatusModels(_statusService.Get(_token));
            var status = statuses.FirstOrDefault(s => (s.IDStatus == task.IDStatus));
            ViewBag.Statuses = new SelectList(statuses, "IDStatus", "Name", IndexOf(statuses, status));
            if(task.DateFinish != null)
            task.DateFinish = task.DateFinish.Value.Date;
            return View(task);
        }

        private int IndexOf(IEnumerable<StatusModel> source, StatusModel value)
        {
            int index = 0;
            var comparer = EqualityComparer<StatusModel>.Default;
            foreach (var item in source)
            {
                if (comparer.Equals(item, value)) return index;
                index++;
            }
            return 0;
        }

        [HttpPost]
        public ActionResult Edit(CreateTaskModel task)
        {
            _taskService.Update(SwapCreateModelToModel(task), _token);
            return RedirectToAction("Edit");
        }

        
        public ActionResult Delete(int id)
        {
            _taskService.Delete(id, _token);
            return RedirectToAction("Index","Category");
        }

        [HttpPost]
        public ActionResult TaskSearch(string title, int idCategory)
        {
            var tasks = SwapToShortModels(_taskService.Search(idCategory,title, _token));
            if (tasks == null)
            {
                ViewBag.Message = "Tasks not found";
                return View();
            }
            return View(tasks);
        }

        #region Swap

        private static ListShortTaskModel SwapToModel(IListShortTaskModel dto)
        {
            return new ListShortTaskModel
            {
                Tasks = dto.Tasks,
                PagingParameter = dto.PagingParameter
            };
        }

        private static ShortTaskModel SwapToShortModel(IShortTaskModel dto)
        {
            return new ShortTaskModel
            {
                IDTask = dto.IDTask,
                IDCategory = dto.IDCategory,
                Name = dto.Name,
                Priority = dto.Priority,
                DateFinish = dto.DateFinish,
                DateFinishString = dto.DateFinishString,
                UserName = dto.UserName
            };
        }

        private static TaskModel SwapToModel(ITaskModel dto)
        {
            return new TaskModel
            {
                IDTask = dto.IDTask,
                IDCategory = dto.IDCategory,
                Name = dto.Name,
                Priority = dto.Priority,
                Description = dto.Description,
                DateFinish = dto.DateFinish,
                DateCreation = dto.DateCreation,
                Status = dto.Status
            };
        }

        private static IEnumerable<ShortTaskModel> SwapToShortModels(IEnumerable<IShortTaskModel> dtoes)
        {
            return dtoes.Select(SwapToShortModel).ToList();

        }

        private static StatusModel SwapToStatusModel(IStatusModel dto)
        {
            return new StatusModel
            {
                IDStatus = dto.IDStatus,
                Name = dto.Name,
            };
        }

        private static IEnumerable<StatusModel> SwapToStatusModels(IEnumerable<IStatusModel> dtoes)
        {
            return dtoes.Select(SwapToStatusModel).ToList();

        }

        private static TaskModel SwapCreateModelToModel(CreateTaskModel createModel)
        {
            return new TaskModel
            {
                IDTask = createModel.IDTask,
                IDCategory = createModel.IDCategory,
                Name = createModel.Name,
                Priority = createModel.Priority,
                Description = createModel.Description,
                DateFinish = createModel.DateFinish,
                DateCreation = createModel.DateCreation,
                Status = new StatusModel { IDStatus = createModel.IDStatus}
            };
        }

        private static CreateTaskModel SwapModelToCreateModel(ITaskModel model)
        {
            return new CreateTaskModel
            {
                IDTask = model.IDTask,
                IDCategory = model.IDCategory,
                Name = model.Name,
                Priority = model.Priority,
                Description = model.Description,
                DateFinish = model.DateFinish,
                DateCreation = model.DateCreation,
                IDStatus = model.Status.IDStatus
            };
        }
        #endregion
    }
}

ToDoList/TDL.AspNet/Views/Task/Create.cshtml
@model TDL.AspNet.Models.CreateTaskModel

@{
    ViewBag.Title = "Create";
    if(DateTime.Now.Month < 10)
    {
        ViewBag.Month = "0" + DateTime.Now.Month;
    }
    else
    {

        ViewBag.Month = DateTime.Now.Month;
    }
    if (DateTime.Now.Day < 10)
    { ViewBag.Day = "0" + DateTime.Now.Day; }
    else { ViewBag.Day = DateTime.Now.Day; }

    ViewBag.Date = DateTime.Now.Year+ "-" + ViewBag.Month + "-" + ViewBag.Day;
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-lg-offset-2">

                <h2 class="text-center text-info">Add new task</h2>


               @using (Html.BeginForm())
               {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="controls">

                        <div class="row">
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_name">Title *</label>
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "form_name", placeholder = "Please enter title *" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_lastname">Priority *</label>
                                    @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", @id = "form_lastname", placeholder = "Please choice level priority *" } })
                                    @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_message">Description </label>
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @id = "form_message", placeholder = "Description for task" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_message">Status </label>
                                    @Html.DropDownListFor(model => model.IDStatus, ViewBag.Statuses as SelectList, new { @id = "form_message", @class = "form-control" })
                                </div>
                            </div>
                        </div>
                            <div class=" col-lg-offset-4 col-md-6">
                                <div class="form-group">
                                    <label for="form_message">Date Finish </label>
                                    @Html.EditorFor(model => model.DateFinish, new { htmlAttributes = new { @class = "form-control", type="date", min= ViewBag.Date } })
                                    @Html.ValidationMessageFor(model => model.DateFinish, "", new { @class = "text-danger" })
                                </div>
                            </div>

                           

                        
                        <div class="col-md-14 top-margin">
                            <input type="submit" class="btn btn-success btn-send col-md-12" value="SAVE TASK">
                        </div>
                    </div>

               }

            </div><!-- /.col-lg-8 col-lg-offset-2 -->

        </div> <!-- /.row-->

    </div> 

ToDoList/TDL.AspNet/Views/Task/Edit.cshtml
@model TDL.AspNet.Models.CreateTaskModel

@{
    ViewBag.Title = "Create";
    if (DateTime.Now.Month < 10)
    {
        ViewBag.Month = "0" + DateTime.Now.Month;
    }
    else
    {

        ViewBag.Month = DateTime.Now.Month;
    }
    if (DateTime.Now.Day < 10)
    { ViewBag.Day = "0" + DateTime.Now.Day; }
    else { ViewBag.Day = DateTime.Now.Day; }

    ViewBag.Date = DateTime.Now.Year + "-" + ViewBag.Month + "-" + ViewBag.Day;
    if(Model.DateFinish != null)
    {
        if (Model.DateFinish.Value.Month < 10)
        {
            ViewBag.Month = "0" + Model.DateFinish.Value.Month;
        }
        else
        {

            ViewBag.Month = Model.DateFinish.Value.Month;
        }
        if (Model.DateFinish.Value.Day < 10)
        { ViewBag.Day = "0" + Model.DateFinish.Value.Day; }
        else { ViewBag.Day = Model.DateFinish.Value.Day; }
        ViewBag.DateFinish = Model.DateFinish.Value.Year + "-" + ViewBag.Month + "-" + ViewBag.Day;
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container well">

    <div class="row">

        <div class="col-lg-8 col-lg-offset-2">

            <h2 class="text-center text-info">Edit task @Model.Name</h2>
            <h2 class="text-right">
                <a href="@Url.Action("Sharing","SharingTask", new { idTask = Model.IDTask, name = Model.Name })">
                    <i class="fa fa-share-square" aria-hidden="true"></i>
                </a>
            </h2>
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDCategory)
                    @Html.HiddenFor(model => model.IDTask)
                    @Html.HiddenFor(model => model.DateCreation)

                    <div class="controls">

                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="Name">Title *</label>
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control",  placeholder = "Please enter title *" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="Priority">Priority *</label>
                                    @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", placeholder = "Please choice level priority *" } })
                                    @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="Description">Description </label>
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Description for task" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="IDStatus">Status </label>
                                    @Html.DropDownListFor(model => model.IDStatus, ViewBag.Statuses as SelectList, new {@class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class=" col-lg-offset-4 col-md-6">
                            <div class="form-group">
                                <label for="DateFinish">Date Finish </label>
                                @Html.Editor("DateFinish", new { htmlAttributes = new { @class = "form-control", type = "date", min = ViewBag.Date, format = "dd/MM/yyyy", value = ViewBag.DateFinish } })
                                @Html.ValidationMessageFor(model => model.DateFinish, "", new { @class = "text-danger" })
                            </div>
                        </div>




                        <div class="col-md-14 top-margin">
                            <input type="submit" class="btn btn-success btn-send col-md-12" value="SAVE TASK">
                        </div>
                    </div>

                }

</div><!-- /.col-lg-8 col-lg-offset-2 -->

    </div> <!-- /.row-->

</div>
<div class="container">
   
    <div class="row">

        <div class="col-lg-8 col-lg-offset-2">
            

            <div class="container well" id="comments">
                <div class="container top-margin se-pre-con"></div>
            </div>
        </div>
    </div>
</div>
        @Scripts.Render("~/comment/script")
        @section scripts
{
            <script type="text/javascript">
                $(document).ready(function () {
                hrefComment = "@Url.Action("Index", "Comment", new { idTask = Model.IDTask })"
        });
            </script>
        }

ToDoList/TDL.AspNet/Views/Task/Index.cshtml
@model TDL.WebApi.Service.Models.ListShortTaskModel
@using TDL.AspNet.Helpers

@if (Model.Tasks.Count() > 0)
{
    <div class="container col-md-8 text-center">
        @using (Html.BeginForm("TaskSearch", "Task"))
        {
        @Html.AntiForgeryToken()

        <div class="form-horizontal  text-center">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="input-group ">
                    <input class="form-control " placeholder="Search task by name" type="text" name="title" />
                    @Html.HiddenFor(model => model.Tasks.FirstOrDefault().IDCategory)
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-search " type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </span>
                </div>
            </div>
        </div>
        }
    </div>
    <div class="table-responsive">
        <table class="table table-background table-hovers">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Priority
                </th>
                <th>
                    DateFinish
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Tasks)
            {
                <tr>
                    <td>
                        <a class="a-des" href="@Url.Action("Edit", "Task", new { id = item.IDTask }, null)">@Html.DisplayFor(modelItem => item.Name)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority)
                    </td>
                    <td>
                        @if (item.DateFinish != null)
                        {
                            @Convert.ToDateTime(item.DateFinish).ToString("dd/MM/yyyy")
                        }
                    </td>

                    <td>
                        <h4>
                            <a href="@Url.Action("Edit", new { id = item.IDTask })">
                                <i class="fa fa-pencil text-success" aria-hidden="true"></i>
                            </a>
                            <a href="@Url.Action("Delete", new { id = item.IDTask })">
                                <i class="fa fa-trash text-danger" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </td>
                </tr>


            }

        </table>
    </div>
    if (Model.PagingParameter.TotalPages > 1)
    {
        <div class="btn-group">
            @Html.PageLinks(Model.PagingParameter.TotalPages, Model.PagingParameter.CurrentPage, x => Url.Action("Index", new { idCategory = Model.Tasks.First().IDCategory, page = x }))
        </div>
        }
        }
        else
        {
        <h3 class="text-warning"> Tasks not found</h3>
        }
        @Scripts.Render("~/task/script")

ToDoList/TDL.AspNet/Views/Task/SharedTask.cshtml
@model TDL.WebApi.Service.Models.ListShortTaskModel
@using TDL.AspNet.Helpers

@if (Model.Tasks.Count() > 0)
{
    <h2 class="text-center text-info">Shared task</h2>
    <div class="table-responsive wells">
        <table class="table table-background table-hovers top-margin ">
            <tr>
                <th>
                    <label class="a-des">Name</label>
                </th>
                <th>
                    <label class="a-des">Priority</label>
                </th>
                <th>
                    <label class="a-des">DateFinish</label>
                </th>
                <th>
                    <label class="a-des">Owner</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Tasks)
            {
                <tr>
                    <td>
                        <a class="compItem a-des" href="@Url.Action("Edit", "Task", new { id = item.IDTask }, null)">@Html.DisplayFor(modelItem => item.Name)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority)
                    </td>
                    <td>
                        @if (item.DateFinish != null)
                    {
                            @Convert.ToDateTime(item.DateFinish).ToString("dd/MM/yyyy")
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        <h4>
                            <a href="@Url.Action("Edit", new { id = item.IDTask })">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </td>
                </tr>


            }

        </table>
    </div>
    if (Model.PagingParameter.TotalPages > 1)
    {
        <div class="btn-group">
            @Html.PageLinks(Model.PagingParameter.TotalPages, Model.PagingParameter.CurrentPage, x => Url.Action("SharedTask", new { page = x }))
        </div>
        }
        }
        else
        {
        <h3 class="text-danger text-canter"> Tasks not found</h3>
        }

ToDoList/TDL.AspNet/Views/Task/TaskSearch.cshtml
@model IEnumerable<TDL.WebApi.Service.Models.ShortTaskModel>

@{
    ViewBag.Title = "TaskSearch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Count() > 0)
{
    <h2 class="text-center text-info">Search result</h2>
    <div class="table-responsive wells">
        <table class="table table-background table-hovers ">
            <tr>
                <th>
                    <label class="a-des">Name</label>
                </th>
                <th>
                    <label class="a-des">Priority</label>
                </th>
                <th>
                    <label class="a-des">DateFinish</label>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a class="compItem a-des" href="@Url.Action("Details", "Test", new { id = item.IDTask }, null)">@Html.DisplayFor(modelItem => item.Name)</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority)
                    </td>
                    <td>
                        @if (item.DateFinish != null)
                        {
                            @Convert.ToDateTime(item.DateFinish).ToString("dd/MM/yyyy")
                        }
                    </td>

                    <td>
                        <h4>
                            <a href="@Url.Action("Edit", new { id = item.IDTask })">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                            <a href="@Url.Action("Delete", new { id = item.IDTask })">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </h4>
                    </td>
                </tr>


            }

        </table>
        </div>
        }
        else
        {
        <h3 class="text-danger text-center"> Tasks not found</h3>
        }